spring.application.name=Blogging_Platform
spring.profiles.active=prod

spring.kafka.producer.retries=10
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.acks=all


spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.path=/graphql
spring.graphql.cors.allowed-origins=*
spring.graphql.cors.allowed-methods=GET,POST

spring.graphql.cors.allowed-headers=*
spring.graphql.cors.allow-credentials=false

spring.kafka.admin.fail-fast=false
spring.kafka.listener.missing-topics-fatal=false
