spring.application.name=BloggingPlatform
spring.profiles.active=prod

spring.kafka.producer.retries=10
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.acks=all
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.path=/graphql
spring.graphql.cors.allowed-origins=*
spring.graphql.cors.allowed-methods=GET,POST

spring.graphql.cors.allowed-headers=*
spring.graphql.cors.allow-credentials=false

spring.kafka.admin.fail-fast=false
spring.kafka.listener.missing-topics-fatal=false

#moderation.service.url  = http://aicontentmoder-service:8089
#moderation.service.url  = http://localhost:8089
management.endpoints.web.exposure.include=info,metrics,health


resilience4j.retry.instances.AIContentModerationService.max-attempts=3
resilience4j.retry.instances.AIContentModerationService.wait-duration=2s

spring.cloud.openfeign.circuitbreaker.enabled=true


spring.cloud.openfeign.client.config.AIContentModerationService.connect-timeout=2000
spring.cloud.openfeign.client.config.AIContentModerationService.read-timeout=3000

resilience4j.circuitbreaker.instances.AIContentModerationService.sliding-window-size=10
resilience4j.circuitbreaker.instances.AIContentModerationService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.AIContentModerationService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.AIContentModerationService.wait-duration-in-open-state=20s
resilience4j.circuitbreaker.instances.AIContentModerationService.permitted-number-of-calls-in-half-open-state=3

resilience4j.ratelimiter.instances.BloggingPlatform.limit-for-period=10
resilience4j.ratelimiter.instances.BloggingPlatform.limit-refresh-period=1s
resilience4j.ratelimiter.instances.BloggingPlatform.timeout-duration=0









